server:
  port: 8081
spring:
  application:
    name: customer-service
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:mem:customerdb
      username: sa
      password:
      driverClassName: org.h2.Driver
    jpa:
      database-platform=org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



